### PR TITLE
Database templates and filler data

### PR DESCRIPTION
**Pull request by drohwedderGFU**
Defined content types, added filler data to database, and updated README with table/field names and types.

### CODE REVIEW

**Comment by chris-hammond** [comment]
What's with all the files in /admin/build? Those look like they should be gitignored...

**Comment by chris-hammond** [comment]
Version-controlling the /db folder just feels wrong. Are we thinking this is a way to easily spin up a demo (essentially database seeding)? What's the long-term plan?

**Comment by drohwedderGFU** [comment]
> Version-controlling the /db folder just feels wrong. Are we thinking this is a way to easily spin up a demo (essentially database seeding)? What's the long-term plan?

I was under the impression that we were going to put some (manually made) filler data in the repo for the next team(s).
I assume a (real) deployment of this would lead us to use an external db anyways, so this could save work for those who want a running prototype/demo.


My cursory googling hasn't led me to any simple seed data methods for strapi/mongodb.

I can remove/gitignore /db if you want, let me know how to proceed!

**Comment by chris-hammond** [comment]
This one looks good to me know. What do you all think?

**Comment by dince16** [comment]
> This one looks good to me know. What do you all think?

I think it looks good and is in a good place for right now

**Pull request merged**
